# Generated by Django 4.2 on 2023-04-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hots',
            new_name='host',
        ),
    ]
