# Generated by Django 4.2 on 2023-05-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_messages_options_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
